<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Drops the per-catalog-row card image generated by the now-removed
 * App\Services\Campaign\CrewCardImageGenerator. Nothing ever rendered it —
 * the Arsenal Sheet and Game Tracker both display the combined per-crew
 * image (campaign_crews.crew_card_front_image) instead, which is unrelated
 * and untouched by this migration.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('campaign_crew_cards', function (Blueprint $table) {
            $table->dropColumn('front_image');
        });
    }

    public function down(): void
    {
        Schema::table('campaign_crew_cards', function (Blueprint $table) {
            $table->string('front_image')->nullable()->after('description');
        });
    }
};
